apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app
  description: Python app which displays time.
  annotations:
    github.com/project-slug: KaushikseetharamNexTurn/python-app
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental
